// ------------------------------------------------------------
// Open Graph / Twitter image constants.
//
// The image itself is generated by src/app/opengraph-image.tsx (a branded
// 1200×630 card). This module is the plain-data reference to it that page
// `generateMetadata` uses as the fallback whenever a tour or blog post has
// no cover image of its own.
//
// See docs/requirements/seo-metadata-og-images.md.
// ------------------------------------------------------------

export const OG_IMAGE_ALT =
  "Travel Trails — private, boutique journeys across Sri Lanka";

/** Site-wide social share image, served by `src/app/opengraph-image.tsx`. */
export const SITE_OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: OG_IMAGE_ALT,
} as const;
